version: '3'
services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: npm start
  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: athlete_db
    ports:
      - "5432:5432"